on: push
name: pushToUpload FTP<->Git
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: fuchsia.viiic.net
        username: testhihihi@fuchsia.viiic.net
        password: ${{ secrets.ftp_password }}
    - name: 🔔 Announce over ntfy.sh 
      steps:
        - run: curl -d "Finished pushing to FTP!" ntfy.sh/ntcedm